import { Inter } from "next/font/google";
import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

import Navbar from "@/components/Navbar";

import PageLayout from "@/components/PageLayout";

export default function RootLayout({ children }) {
	return (
		<>
			<Navbar />

			<main className={inter.className}>
				<PageLayout> {children}</PageLayout>
			</main>
		</>
	);
}
